package org.integrallis.drools.flows

rule "MatchSomeOtherObjectWithFoo"
	ruleflow-group "decision"
	when
		SomeOtherObject(someOtherValue == "foo")
	then 
		insert(new SomeObject("Process One"));
end

rule "MatchSomeOtherObjectWithBar"
	ruleflow-group "decision"
	when
		SomeOtherObject(someOtherValue == "bar")
	then 
		insert(new SomeObject("Process Two"));
end

rule "DoSomethingInGroup1"
	ruleflow-group "group1"
	when
		SomeObject()
	then 
		System.out.println("We are in Process One!");
end

rule "DoSomethingInGroup2"
	ruleflow-group "group2"
	when
		SomeObject()
	then 
		System.out.println("We are in Process Two!");
end